# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be95b0db0ee1e98b722ef01b017facd11a296e3c11df09ef48de19929b113a795bab3587ac9800099fed8eb87c576912ddd8569993f0cae06796282323bbc6b4

test:
  secret_key_base: 9330510fb5d3e26b8599dd2929c0324b396aa331c5817e61cd05794098aea3711cdf334cfc2edd2e66c4bfa73d6c9264a58f3cb660d3578f40eca7675ad85a3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
